name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    tags:
      - 'v*.*.*'

jobs:
  # Job для проверки кода и запуска тестов
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test -v ./...

  # Job для сборки и публикации в DockerHub
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: wascos/final-main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/parcel-app:${{ github.ref_name }}
